#  Copyright (c) 2025-2026 National Institute for Space Research (INPE) (https://www.gov.br/inpe/pt-br). Documentation, source code, and more details about the AdaptaBrasil project are available at: https://github.com/AdaptaBrasil/.
"""
Module for generating text pattern combinations.

This module defines the `CombinationsProcessing` class, which handles the generation
and validation of string combinations (e.g., 'CODE-YEAR-SCENARIO') used in
data validation and structure verification.
"""

from typing import List, Tuple, Any


class CombinationsProcessing:
    """
    Utility class for generating and validating identifier combinations.

    Provides static methods to create expected combination strings based on base codes,
    temporal ranges, and scenario symbols, and to identify unexpected (extra) combinations.
    """

    def __init__(self) -> None:
        """Initialize the CombinationsProcessing class."""
        pass

    @staticmethod
    def generate_combinations(code: str, start_year: int, temporal_symbols: List[Any], scenario_symbols: List[Any]) -> List[str]:
        """
        Generate a list of combination strings based on code, time, and scenarios.

        Creates identifiers in the format 'code-year-scenario'. The output includes
        a base combination (code-start_year) followed by combinations for subsequent
        years and all provided scenario symbols.

        Args:
            code (str): Base code for the combinations.
            start_year (int): The initial year (base year).
            temporal_symbols (List[Any]): List of temporal symbols (e.g., years).
            scenario_symbols (List[Any]): List of scenario symbols (e.g., SSPs).

        Returns:
            List[str]: List of generated combination strings (e.g., ['X-2020', 'X-2030-SSP1', ...]).
        """
        combinations = [f"{code}-{start_year}"]
        for year in temporal_symbols[1:]:
            for symbol in scenario_symbols:
                combinations.append(f"{code}-{year}-{symbol}")
        return combinations

    @staticmethod
    def find_extra_combinations(expected_combinations: List[str], actual_combinations: List[str]) -> Tuple[bool, List[str]]:
        """
        Identify extra combinations that are present but not expected.

        Compares the actual list of combinations found against the expected list
        generated by business rules.

        Args:
            expected_combinations (List[str]): List of valid/expected combinations.
            actual_combinations (List[str]): List of combinations actually found in the data.

        Returns:
            Tuple[bool, List[str]]:
                - bool: True if any extra combinations exist, False otherwise.
                - List[str]: The list of extra (unexpected) combination strings.
        """
        extras = list(set(actual_combinations) - set(expected_combinations))
        return bool(extras), extras
