#  Copyright (c) 2025 Mário Carvalho (https://github.com/MarioCarvalhoBr).
import os
from enchant import Broker, Dict
from pathlib import Path
from typing import List


class DictionaryManager:
    """Gerenciador de dicionários Enchant"""

    def __init__(self, lang_dict_spell: str):
        self.lang_dict_spell = lang_dict_spell
        self.dictionary = None
        self.broker = None
        self._errors = []
        self.path_dictionary: Path = Path(__file__).resolve().parents[3] / 'static' / 'dictionaries'

        self._setup_paths()

    def _setup_paths(self) -> None:
        """Configura os caminhos dos arquivos de dicionário"""
        enchant_config_dir = self.path_dictionary

        # Define o diretório de configuração do Enchant
        os.environ["ENCHANT_CONFIG_DIR"] = str(enchant_config_dir)

    def validate_dictionary(self) -> List[str]:
        """Valida se o dicionário existe"""
        try:
            self.broker = Broker()
            if not self.broker.dict_exists(self.lang_dict_spell):
                self._errors.append(f"Dicionário {self.lang_dict_spell} não encontrado")
        except Exception as e:
            self._errors.append(f"Erro ao verificar dicionário: {e}")

        return self._errors

    def initialize_dictionary(self, list_words_user) -> Dict | None:
        """Inicializa o dicionário Enchant e adiciona palavras extras"""
        try:
            if not self.broker:
                self.broker = Broker()

            self.dictionary = self.broker.request_dict(self.lang_dict_spell)

            # Adiciona palavras extras do arquivo extra-words.dic
            self._load_extra_words()

            # Adiciona palavras do usuário
            for word in list_words_user:
                if word and not word.startswith('#'):
                    self.dictionary.add(word)

            return self.dictionary
        except Exception as e:
            self._errors.append(f"Erro ao inicializar dicionário {self.lang_dict_spell}: {e}")

    def _load_extra_words(self) -> None:
        """Carrega palavras extras do arquivo extra-words.dic"""
        try:
            extra_words_path = self.path_dictionary / 'extra-words.dic'

            if extra_words_path.exists():
                with open(extra_words_path, 'r', encoding='utf-8') as file:
                    for line in file:
                        word = line.strip()
                        if word and not word.startswith('#'):  # Ignora linhas vazias e comentários
                            self.dictionary.add(word)
            else:
                self._errors.append("Arquivo extra-words.dic não encontrado. Reporte o erro ao administrador do sistema.")

        except Exception as e:
            # Log do erro mas não interrompe a execução
            self._errors.append(f"Aviso: Não foi possível carregar palavras extras: {e}")

    def __del__(self):
        """
        Destructor to ensure temporary files are cleaned up when the object is destroyed.
        """
        try:
            self.clean_temporary_files()
        except Exception:
            # Ignore errors during cleanup in destructor
            pass

    def clean_temporary_files(self):
        """
        Remove temporary files generated by Enchant (.dic and .exc files).
        These files are created when adding custom words to the dictionary.
        """

        # First, properly cleanup the broker and dictionary
        try:
            if self.dictionary:
                # Free the dictionary resource
                self.dictionary = None

            if self.broker:
                # Cleanup broker resources
                self.broker = None

        except Exception as e:
            self._errors.append(f"Warning: Could not cleanup Enchant resources: {e}")

        # Remove temporary dictionary files
        temp_files_to_remove = [
            self.path_dictionary / f"{self.lang_dict_spell}.dic",
            self.path_dictionary / f"{self.lang_dict_spell}.exc"
        ]

        for temp_file in temp_files_to_remove:
            try:
                if temp_file.exists():
                    temp_file.unlink()
            except Exception as e:
                self._errors.append(f"Warning: Could not remove temporary file {temp_file}: {e}")
