name: Run Ubuntu 24.04.1 LTS with Python 3.12 versions

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04  # Especifica o Ubuntu 24.04 como o ambiente
    # runs-on: ubuntu-latest  # Especifica a última versão do Ubuntu como o ambiente
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      #--- UPDATE PIP
      - name: Update pip upgrade
        run: |
          python -m pip install --upgrade pip
  
      #--- DISPLAY PYTHON VERSION
      - name: Display Python and PIP version
        run: 
          python -c "import sys; print(sys.version)"
          python -m pip --version
      
      #--- SETUP YOUR ENVIRONMENT HERE: INSTALL THE NECESSARY SOFTWARES FOR YOUR PROJECT
      ## INSTALL WKHTMLTOPDF
      - name: Install WKHtmlToPdf on Ubuntu
        run: |
          sudo apt-get update --fix-missing -y
          sudo apt-get upgrade -y
          sudo apt-get install -y wkhtmltopdf
      ## INSTALL HUNSPELL
      - name: Install Hunspell on Ubuntu
        run: |
          sudo apt-get update --fix-missing -y
          sudo apt-get install -y libhunspell-dev
          sudo apt-get install -y hunspell-en-us hunspell-pt-br
      
      #--- DEPENDENCIES
      ## INSTALL DEPENDENCIES PYTHON
      - name: Install config packages
        run: |
          pip install enum34
          pip install coverage
          pip install ruff
      ## INSTALL DEPENDENCIES FROM REQUIREMENTS.TXT
      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      #--- LINT
      ## LINT YOUR CODE HERE
      - name: Lint with Ruff
        run: |
          ruff check . --target-version=py310
        continue-on-error: true
      
      #--- TEST
      ## TEST YOUR CODE HERE
      - name: Test with pytest and Generate Coverage Report
        run: |
          coverage run -m pytest  -v -s
          coverage report -m

      #--- RUN    
      ## RUN YOUR SCRIPT HERE
      - name: Run code with Python
        run:
          bash scripts/run_main_pipeline.sh 
